name: Upload to DAFNI

on:
  release:
    types: [published]

jobs:
  release:
    name: Upload to DAFNI
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Docker Build
        run: docker build -t flood-impact-model-v2 .

      - name: Compress docker image
        run: docker save flood-impacts-dafni | gzip > flood-impacts.tar.gz

      - name: Set tag as env
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Upload to DAFNI
        uses: dafnifacility/dafni-model-uploader@v1.9
        with:
          definition-path: './model-definition.yml'
          image-path: './flood-impacts.tar.gz'
          username: ${{ secrets.DAFNI_SERVICE_ACCOUNT_USERNAME }}
          password: ${{ secrets.DAFNI_SERVICE_ACCOUNT_PASSWORD }}
          version-message: ${{ env.TAG }}
          parent-model: "53e77958-44af-402c-9fbc-91aa679008a3"
